language: php
php:
  - '7.0'
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
#    - secure: "UkF2CHX0lUZ...VI/LE=" # DOCKER_EMAIL
#    - secure: "Z3fdBNPt5hR...VI/LE=" # DOCKER_USER
#    - secure: "F4XbD6WybHC...VI/LE=" # DOCKER_PASS
after_success:
#  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=netsyos/docker-base
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
#  - docker push $REPO
